<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetFramework>$(RepositoryTargetFramework)-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\Launcher.Pet\Launcher.Pet.csproj" /></ItemGroup>
  <ItemGroup><None Update="Resources\**\*.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><Compile Update="Windows\*.cs;Debug\*.cs"><SubType>Code</SubType></Compile></ItemGroup>
</Project>


